version: 1.0.{build}
image: Visual Studio 2017

skip_commits:
  # Regex for matching commit message
  message: /\(doc\).*/

init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
